title: "Felzartamab and ABMR Guide"
description: "Guide to the effect of felzartamab anti-CD38 treatment on the molecular phenotype of antibody-mediated rejection in kidney transplant biopsies."
theme: jekyll-theme-minimal